### ISSUE TITLE
Web radio support

### ISSUE THREAD

**Issue by xabolcs** [w0rp/xmms2-mpris#5]
First of all
### THANK you for this addon! :tada: 
It adds a lot of value to User Experience on Gnome!

### Feature request
I use XMMS2 for listening web radios and they just use `title` as `Artist - Title` with empty `artist`.
It would be nice to split that web radio title into real artist and title.

I took a few screenshots with the help of [Mpris Indicator Button](https://extensions.gnome.org/extension/1379/mpris-indicator-button/), see below!

![Screenshot from 2021-07-02 11-35-39](https://user-images.githubusercontent.com/568751/124255097-13aac480-db2a-11eb-85ca-18c4bf1136f9.png) 
![Screenshot from 2021-07-02 11-31-51](https://user-images.githubusercontent.com/568751/124255098-14435b00-db2a-11eb-9b37-bd3b0b06c74d.png)

```
$ xmms2 info
[server] added = 1571062988
[plugin/mad] bitrate = 128000
[server] chain = curl:icymetaint:magic:mad:segment
[plugin/curl] channel = Radio Antena Rock
[plugin/mad] channels = 2
[plugin/curl] genre = Rock
[server] id = 5
[server] laststarted = 1625218234
[plugin/magic] mime = audio/mpeg
[plugin/mad] sample_format = S16
[plugin/mad] samplerate = 44100
[server] status = 1
[server] timesplayed = 187
[plugin/icymetaint] title = TUBLATANKA - DNES
[server] url = http://stream.radioservices.sk/antena-hi.mp3

$ xmms2 info
[server] added = 1571062988
[plugin/mad] bitrate = 128000
[server] chain = curl:icymetaint:magic:mad:segment
[plugin/curl] channel = Radio Antena Rock
[plugin/mad] channels = 2
[plugin/curl] genre = Rock
[server] id = 5
[server] laststarted = 1625218234
[plugin/magic] mime = audio/mpeg
[plugin/mad] sample_format = S16
[plugin/mad] samplerate = 44100
[server] status = 1
[server] timesplayed = 187
[plugin/icymetaint] title = Radio Antena Rock - www.antenarock.sk
[server] url = http://stream.radioservices.sk/antena-hi.mp3

```

#### Programs, versions
* Ubuntu LTS 20.04
* Gnome 3.36
* `xmms2` (`0.8+dfsg-18.2ubuntu3`) from installing `xmms2-plugin-all`
* Mpris Indicator Button [Gnome Extension](https://extensions.gnome.org/extension/1379/mpris-indicator-button/)

**Comment by w0rp** [comment]
Job's done.

**Comment by w0rp** [comment]
I re-opened the issue based on your comment on the pull request. If there's still something wrong with it, just open another pull request. I just slapped together this C code based on what works well enough on my machine.

**Comment by xabolcs** [comment]
I use XMMS2 only for webradio, but I had to test it against normal files! :sweat_smile:

**Comment by xabolcs** [comment]
For the record: the "webradio support" I provided surfaces the following problem:
```
Mar 21 01:27:28 gnome-shell[6327]: Received faulty track artist metadata from org.mpris.MediaPlayer2.xmms2; expected an array of strings, got Memoria Avenue (string)
```
The argument is valid: the [artist metadata should be list of strings](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#xesam:artist). :shrug: 


Another problem is that is spams the syslog: its logged in every second. :confused:

**Comment by w0rp** [comment]
https://github.com/w0rp/xmms2-mpris/blob/158a239205727e447cd4bcaff71437b70706f603/src/mpris.c#L48 The problem will be on this line. That string will need to be changed to a list of strings, however you do that with gobject.

**Comment by xabolcs** [comment]
> ... however you do that with `gobject`.

I tried and failed with my copy-paste-things-from-SO level C knowledge. :sweat_smile:

**Comment by w0rp** [comment]
@xabolcs I should have fixed this now. Give it a try. The artists are now sent as an array of strings.

I'll tag this commit with a v1.0.0 tag, as I think this project is stable enough now.

**Comment by w0rp** [comment]
Turns out I actually already have a v1.0.0 tag, so this is v1.0.1 now.

**Comment by xabolcs** [comment]
Log is clean now!

Thank you very much! :+1:
